### PR TITLE
Kompile uses new type inference algorithm

### PR DESCRIPTION
**Pull request by dkcumming**
A new type inference algorithm has been introduced to K. This PR opts into using that algorithm by setting the appropriate flags in `kbuild.toml`

### CODE REVIEW

**Review by Baltoli — APPROVED** [review]
Looks good; when https://github.com/runtimeverification/pyk/pull/767 is finalised and merged you should be able to use the new feature directly via Pyk.

**Review by Baltoli — CHANGES_REQUESTED** [review]
Ah, in fact it [doesn't look like this is in fact supported](https://github.com/runtimeverification/pyk/blob/master/src/pyk/kbuild/project.py#L109-L127) via `kbuild.toml`. Probably best to wait and use the Pyk feature I linked above.

**Comment by yanliu18** [comment]
I am popping this up since the type-inference feature is supported by pyk by PR https://github.com/runtimeverification/pyk/pull/767.

**Comment by dkcumming** [comment]
Created an issue [here](https://github.com/runtimeverification/pyk/issues/788)

**Comment by dkcumming** [comment]
@Baltoli Things should be working now, I am still a bit unsure how to determine if it is using the new algorithm or not. How would be determine this? If you would like to see differences in timing I am recording local timing in #308

**Review by Baltoli — APPROVED** [review]
Looks good to me! Timing probably won't be _hugely_ different I suspect.

**Pull request merged**
